import type { Routes } from '@angular/router';
import { FeaturePlaceholderComponent } from '../../shared/ui/feature-placeholder/feature-placeholder.component';

const placeholder = (screen: string) => ({
  component: FeaturePlaceholderComponent,
  data: { feature: 'Accounting', screen, phase: 'Phase 8' },
});

export const ACCOUNTING_ROUTES: Routes = [
  { path: 'masters', ...placeholder('Accounting Masters') },
  { path: 'transactions', ...placeholder('Accounting Transactions') },
  { path: 'reports', ...placeholder('Accounting Reports') },

  // masters
  { path: 'AccountsView', ...placeholder('Accounts View') },
  { path: 'AccountsMaster', ...placeholder('Accounts Master') },
  { path: 'BankView', ...placeholder('Bank View') },
  { path: 'BankMaster', ...placeholder('Bank Master') },
  { path: 'ChequemanagementView', ...placeholder('Cheque Management View') },
  { path: 'ChequemanagementMaster', ...placeholder('Cheque Management Master') },
  { path: 'AccountTree', ...placeholder('Account Tree') },
  { path: 'HsnCodes', ...placeholder('HSN Codes') },
  { path: 'SubCategory', ...placeholder('Sub Category') },

  // transactions
  { path: 'GeneralreceiptView', ...placeholder('General Receipt View') },
  { path: 'GeneralreceiptNew', ...placeholder('General Receipt New') },
  { path: 'GeneralreceiptNew/:id', ...placeholder('General Receipt New') },
  { path: 'PaymentvoucherView', ...placeholder('Payment Voucher View') },
  { path: 'PaymentvoucherNew', ...placeholder('Payment Voucher New') },
  { path: 'PaymentvoucherNew/:id', ...placeholder('Payment Voucher New') },
  { path: 'JournalvoucherView', ...placeholder('Journal Voucher View') },
  { path: 'JournalvoucherNew', ...placeholder('Journal Voucher New') },
  { path: 'JournalvoucherNew/:id', ...placeholder('Journal Voucher New') },
  { path: 'TDSPaymentvoucher', ...placeholder('TDS Payment Voucher') },
  { path: 'TdsPaymentvoucherView', ...placeholder('TDS Payment Voucher View') },
  { path: 'ChequesonHandNew', ...placeholder('Cheques On Hand') },
  { path: 'ChequesinBankNew', ...placeholder('Cheques in Bank') },
  { path: 'ChequesIssuedNew', ...placeholder('Cheques Issued') },
  { path: 'GstVoucher', ...placeholder('GST Voucher') },
  { path: 'GstpaymentVocher', ...placeholder('GST Payment Voucher') },
  { path: 'FundTransfer', ...placeholder('Fund Transfer') },
  { path: 'PendingFundTransfer', ...placeholder('Pending Fund Transfer') },

  // reports
  { path: 'CashBook', ...placeholder('Cash Book') },
  { path: 'CashBook/:id', ...placeholder('Cash Book') },
  { path: 'BankBook', ...placeholder('Bank Book') },
  { path: 'BankBook/:id', ...placeholder('Bank Book') },
  { path: 'AccountLedger', ...placeholder('Account Ledger') },
  { path: 'AccountLedger/:id', ...placeholder('Account Ledger') },
  { path: 'DayBook', ...placeholder('Day Book') },
  { path: 'DayBook/:id', ...placeholder('Day Book') },
  { path: 'TrialBalance', ...placeholder('Trial Balance') },
  { path: 'TrialBalance/:id', ...placeholder('Trial Balance') },
  { path: 'PartyLedger', ...placeholder('Party Ledger') },
  { path: 'PartyLedger/:id', ...placeholder('Party Ledger') },
  { path: 'BalanceSheet', ...placeholder('Balance Sheet') },
  { path: 'BalanceSheet/:id', ...placeholder('Balance Sheet') },
  { path: 'ProfitAndLoss', ...placeholder('Profit & Loss') },
  { path: 'ProfitAndLoss/:id', ...placeholder('Profit & Loss') },
  { path: 'ComparisionTrialBalance', ...placeholder('Comparison Trial Balance') },
  { path: 'BRStatment', ...placeholder('Bank Recon Statement') },
  { path: 'BRStatmentNew', ...placeholder('Bank Recon Statement (New)') },
  { path: 'JournalvoucherReport', ...placeholder('Journal Voucher Report') },
  { path: 'PaymentVoucherReports', ...placeholder('Payment Voucher Reports') },
  { path: 'GeneralReceiptReports', ...placeholder('General Receipt Reports') },
  { path: 'TdsPaymentVoucherReports', ...placeholder('TDS Payment Voucher Reports') },
  { path: 'GstReportNew', ...placeholder('GST Report') },
  { path: 'AgeingReport', ...placeholder('Ageing Report') },
  { path: 'JvList', ...placeholder('JV List') },
  { path: 'LedgerExtract', ...placeholder('Ledger Extract') },
  { path: 'ChequeEnquiry', ...placeholder('Cheque Enquiry') },
  { path: 'ChequeCancel', ...placeholder('Cheque Cancel') },
  { path: 'ChequeReturn', ...placeholder('Cheque Return') },
  { path: 'IssuedCheque', ...placeholder('Issued Cheque') },
  { path: 'SubaccountLedgerreports', ...placeholder('Subaccount Ledger') },
  { path: 'SubledgerSummary', ...placeholder('Subledger Summary') },
  { path: 'AccountLedgerMigration', ...placeholder('Account Ledger Migration') },
  { path: 'AccountLedgerMigration/:id', ...placeholder('Account Ledger Migration') },
  { path: 'BrsReports', ...placeholder('BRS Reports') },
  { path: 'BRSPreview', ...placeholder('BRS Preview') },
  { path: 'BRSPreview/:id', ...placeholder('BRS Preview') },
];
